
(install
 (section (site (camomile charmaps)))
 (files
   ANSI_X3%2E110-1983.mar
   NAPLPS.mar
   CSA_T500-1983.mar
   ISO-IR-99.mar
   ANSI_X3%2E4-1968.mar
   CP367.mar
   IBM367.mar
   US.mar
   US-ASCII.mar
   ISO646-US.mar
   ASCII.mar
   ISO_646%2EIRV%3A1991.mar
   ANSI_X3%2E4-1986.mar
   ISO-IR-6.mar
   ARMSCII-8.mar
   ASMO_449.mar
   ISO-IR-89.mar
   ARABIC7.mar
   ISO_9036.mar
   BIG5.mar
   BIG5-CP950.mar
   BIG5-HKSCS.mar
   BIG5HKSCS.mar
   BRF.mar
   BS_4730.mar
   UK.mar
   GB.mar
   ISO646-GB.mar
   ISO-IR-4.mar
   BS_VIEWDATA.mar
   ISO-IR-47.mar
   CP10007.mar
   CP1125.mar
   IBM848.mar
   RUSCII.mar
   CP1250.mar
   MS-EE.mar
   CP1251.mar
   MS-CYRL.mar
   CP1252.mar
   MS-ANSI.mar
   CP1253.mar
   MS-GREEK.mar
   CP1254.mar
   MS-TURK.mar
   CP1255.mar
   MS-HEBR.mar
   CP1256.mar
   MS-ARAB.mar
   CP1257.mar
   WINBALTRIM.mar
   CP1258.mar
   CP737.mar
   CP775.mar
   CP932.mar
   CP949.mar
   CSA_Z243%2E4-1985-1.mar
   CA.mar
   CSA7-1.mar
   ISO646-CA.mar
   ISO-IR-121.mar
   CSA_Z243%2E4-1985-2.mar
   CSA7-2.mar
   ISO646-CA2.mar
   ISO-IR-122.mar
   CSA_Z243%2E4-1985-GR.mar
   ISO-IR-123.mar
   CSN_369103.mar
   ISO-IR-139.mar
   CWI.mar
   CP-HU.mar
   CWI-2.mar
   DEC-MCS.mar
   DEC.mar
   DIN_66003.mar
   ISO646-DE.mar
   DE.mar
   ISO-IR-21.mar
   DS_2089.mar
   DK.mar
   ISO646-DK.mar
   DS2089.mar
   EBCDIC-AT-DE.mar
   EBCDIC-AT-DE-A.mar
   EBCDIC-CA-FR.mar
   EBCDIC-DK-NO.mar
   EBCDIC-DK-NO-A.mar
   EBCDIC-ES.mar
   EBCDIC-ES-A.mar
   EBCDIC-ES-S.mar
   EBCDIC-FI-SE.mar
   EBCDIC-FI-SE-A.mar
   EBCDIC-FR.mar
   EBCDIC-IS-FRISS.mar
   FRISS.mar
   EBCDIC-IT.mar
   EBCDIC-PT.mar
   EBCDIC-UK.mar
   EBCDIC-US.mar
   ECMA-CYRILLIC.mar
   ISO-IR-111.mar
   ES.mar
   ISO646-ES.mar
   ISO-IR-17.mar
   ES2.mar
   ISO646-ES2.mar
   ISO-IR-85.mar
   EUC-JISX0213.mar
   EUC-JP.mar
   EUC-JP-MS.mar
   EUC-KR.mar
   EUC-TW.mar
   GB18030.mar
   GB2312.mar
   GBK.mar
   WINDOWS-936.mar
   MS936.mar
   CP936.mar
   GB_1988-80.mar
   ISO646-CN.mar
   CN.mar
   ISO-IR-57.mar
   GEORGIAN-ACADEMY.mar
   GEORGIAN-PS.mar
   GOST_19768-74.mar
   ISO-IR-153.mar
   ST_SEV_358-88.mar
   GREEK-CCITT.mar
   ISO-IR-150.mar
   GREEK7.mar
   ISO-IR-88.mar
   GREEK7-OLD.mar
   ISO-IR-18.mar
   HP-GREEK8.mar
   HP-ROMAN8.mar
   R8.mar
   ROMAN8.mar
   HP-ROMAN9.mar
   R9.mar
   ROMAN9.mar
   HP-THAI8.mar
   THAI8.mar
   HP-TURKISH8.mar
   TURKISH8.mar
   IBM037.mar
   EBCDIC-CP-NL.mar
   EBCDIC-CP-WT.mar
   EBCDIC-CP-CA.mar
   EBCDIC-CP-US.mar
   CP037.mar
   IBM038.mar
   CP038.mar
   EBCDIC-INT.mar
   IBM1004.mar
   OS2LATIN1.mar
   CP1004.mar
   IBM1026.mar
   1026.mar
   CP1026.mar
   IBM1047.mar
   1047.mar
   CP1047.mar
   IBM-1047.mar
   IBM1124.mar
   CP1124.mar
   IBM1129.mar
   CP1129.mar
   IBM1132.mar
   CP1132.mar
   IBM1133.mar
   IBM1162.mar
   CP1133.mar
   IBM1160.mar
   CP1160.mar
   IBM1161.mar
   CP1161.mar
   IBM1163.mar
   CP1163.mar
   IBM1164.mar
   CP1164.mar
   IBM256.mar
   EBCDIC-INT1.mar
   IBM273.mar
   CP273.mar
   IBM274.mar
   CP274.mar
   EBCDIC-BE.mar
   IBM275.mar
   CP275.mar
   EBCDIC-BR.mar
   IBM277.mar
   EBCDIC-CP-NO.mar
   EBCDIC-CP-DK.mar
   IBM278.mar
   EBCDIC-CP-SE.mar
   EBCDIC-CP-FI.mar
   CP278.mar
   IBM280.mar
   EBCDIC-CP-IT.mar
   CP280.mar
   IBM281.mar
   CP281.mar
   EBCDIC-JP-E.mar
   IBM284.mar
   EBCDIC-CP-ES.mar
   CP284.mar
   IBM285.mar
   EBCDIC-CP-GB.mar
   CP285.mar
   IBM290.mar
   EBCDIC-JP-KANA.mar
   CP290.mar
   IBM297.mar
   EBCDIC-CP-FR.mar
   CP297.mar
   IBM420.mar
   EBCDIC-CP-AR1.mar
   CP420.mar
   IBM423.mar
   EBCDIC-CP-GR.mar
   CP423.mar
   IBM424.mar
   EBCDIC-CP-HE.mar
   CP424.mar
   IBM437.mar
   437.mar
   CP437.mar
   IBM500.mar
   EBCDIC-CP-CH.mar
   EBCDIC-CP-BE.mar
   500V1.mar
   500.mar
   CP500.mar
   IBM850.mar
   850.mar
   CP850.mar
   IBM851.mar
   851.mar
   CP851.mar
   IBM852.mar
   852.mar
   CP852.mar
   IBM855.mar
   855.mar
   CP855.mar
   IBM856.mar
   856.mar
   CP856.mar
   IBM857.mar
   857.mar
   CP857.mar
   IBM860.mar
   860.mar
   CP860.mar
   IBM861.mar
   CP-IS.mar
   861.mar
   CP861.mar
   IBM862.mar
   862.mar
   CP862.mar
   IBM863.mar
   863.mar
   CP863.mar
   IBM864.mar
   CP864.mar
   IBM865.mar
   865.mar
   CP865.mar
   IBM866.mar
   866.mar
   CP866.mar
   IBM866NAV.mar
   866NAV.mar
   CP866NAV.mar
   IBM868.mar
   CP-AR.mar
   CP868.mar
   IBM869.mar
   CP-GR.mar
   869.mar
   CP869.mar
   IBM870.mar
   EBCDIC-CP-YU.mar
   EBCDIC-CP-ROECE.mar
   CP870.mar
   IBM871.mar
   EBCDIC-CP-IS.mar
   CP871.mar
   IBM874.mar
   WINDOWS-874.mar
   CP874.mar
   IBM875.mar
   EBCDIC-GREEK.mar
   CP875.mar
   IBM880.mar
   EBCDIC-CYRILLIC.mar
   CP880.mar
   IBM891.mar
   CP891.mar
   IBM903.mar
   CP903.mar
   IBM904.mar
   904.mar
   CP904.mar
   IBM905.mar
   EBCDIC-CP-TR.mar
   CP905.mar
   IBM918.mar
   EBCDIC-CP-AR2.mar
   CP918.mar
   IBM922.mar
   CP922.mar
   IEC_P27-1.mar
   ISO-IR-143.mar
   INIS.mar
   ISO-IR-49.mar
   INIS-8.mar
   ISO-IR-50.mar
   INIS-CYRILLIC.mar
   ISO-IR-51.mar
   INVARIANT.mar
   ISO-IR-170.mar
   ISIRI-3342.mar
   ISO-8859-1.mar
   CP819.mar
   IBM819.mar
   L1.mar
   LATIN1.mar
   ISO_8859-1.mar
   ISO_8859-1%3A1987.mar
   ISO-IR-100.mar
   ISO-8859-10.mar
   LATIN6.mar
   L6.mar
   ISO_8859-10.mar
   ISO_8859-10%3A1992.mar
   ISO-IR-157.mar
   ISO-8859-11.mar
   ISO-8859-13.mar
   L7.mar
   LATIN7.mar
   ISO-IR-179.mar
   ISO-8859-14.mar
   L8.mar
   LATIN8.mar
   ISO-8859-15.mar
   LATIN-9.mar
   ISO_8859-15.mar
   ISO-8859-16.mar
   L10.mar
   LATIN10.mar
   ISO_8859-16.mar
   ISO_8859-16%3A2001.mar
   ISO-IR-226.mar
   ISO-8859-2.mar
   L2.mar
   LATIN2.mar
   ISO_8859-2.mar
   ISO_8859-2%3A1987.mar
   ISO-IR-101.mar
   ISO-8859-3.mar
   L3.mar
   LATIN3.mar
   ISO_8859-3.mar
   ISO_8859-3%3A1988.mar
   ISO-IR-109.mar
   ISO-8859-4.mar
   L4.mar
   LATIN4.mar
   ISO_8859-4.mar
   ISO_8859-4%3A1988.mar
   ISO-IR-110.mar
   ISO-8859-5.mar
   CYRILLIC.mar
   ISO_8859-5.mar
   ISO_8859-5%3A1988.mar
   ISO-IR-144.mar
   ISO-8859-6.mar
   ARABIC.mar
   ASMO-708.mar
   ECMA-114.mar
   ISO_8859-6.mar
   ISO_8859-6%3A1987.mar
   ISO-IR-127.mar
   ISO-8859-7.mar
   GREEK8.mar
   GREEK.mar
   ECMA-118.mar
   ELOT_928.mar
   ISO_8859-7.mar
   ISO_8859-7%3A1987.mar
   ISO_8859-7%3A2003.mar
   ISO-IR-126.mar
   ISO-8859-8.mar
   HEBREW.mar
   ISO_8859-8.mar
   ISO_8859-8%3A1988.mar
   ISO-IR-138.mar
   ISO-8859-9.mar
   L5.mar
   LATIN5.mar
   ISO_8859-9.mar
   ISO_8859-9%3A1989.mar
   ISO-IR-148.mar
   ISO-8859-9E.mar
   ISO-IR-197.mar
   ISO-IR-209.mar
   ISO-IR-90.mar
   ISO_6937-2%3A1983.mar
   ISO_10367-BOX.mar
   ISO-IR-155.mar
   ISO_11548-1.mar
   ISO%2FTR_11548-1.mar
   ISO_2033-1983.mar
   E13B.mar
   ISO-IR-98.mar
   ISO_5427.mar
   KOI-7.mar
   ISO-IR-37.mar
   ISO_5427-EXT.mar
   ISO_5427%3A1981.mar
   ISO-IR-54.mar
   ISO_5428.mar
   ISO_5428%3A1980.mar
   ISO-IR-55.mar
   ISO_646%2EBASIC.mar
   ISO_646%2EBASIC%3A1983.mar
   REF.mar
   ISO_646%2EIRV.mar
   IRV.mar
   ISO_646%2EIRV%3A1983.mar
   ISO-IR-2.mar
   ISO_6937.mar
   ISO6937.mar
   ISO_6937%3A1992.mar
   ISO-IR-156.mar
   ISO_6937-2-25.mar
   ISO-IR-152.mar
   ISO_6937-2-ADD.mar
   ISO-IR-142.mar
   ISO_8859-SUPP.mar
   LATIN1-2-5.mar
   ISO-IR-154.mar
   IT.mar
   ISO646-IT.mar
   ISO-IR-15.mar
   JIS_C6220-1969-RO.mar
   ISO646-JP.mar
   JP.mar
   ISO-IR-14.mar
   JIS_C6229-1984-B.mar
   JP-OCR-B.mar
   ISO646-JP-OCR-B.mar
   ISO-IR-92.mar
   JIS_X0201.mar
   X0201.mar
   JOHAB.mar
   JUS_I%2EB1%2E002.mar
   YU.mar
   JS.mar
   ISO646-YU.mar
   ISO-IR-141.mar
   JUS_I%2EB1%2E003-MAC.mar
   ISO-IR-147.mar
   MACEDONIAN.mar
   JUS_I%2EB1%2E003-SERB.mar
   SERBIAN.mar
   ISO-IR-146.mar
   KOI-8.mar
   KOI8-R.mar
   KOI8-RU.mar
   KOI8-T.mar
   KOI8-U.mar
   KSC5636.mar
   ISO646-KR.mar
   LATIN-GREEK.mar
   ISO-IR-19.mar
   LATIN-GREEK-1.mar
   ISO-IR-27.mar
   MAC-CYRILLIC.mar
   MAC-IS.mar
   MAC-SAMI.mar
   MAC-UK.mar
   MACINTOSH.mar
   MAC.mar
   MIK.mar
   MSZ_7795%2E3.mar
   HU.mar
   ISO646-HU.mar
   ISO-IR-86.mar
   NATS-DANO.mar
   ISO-IR-9-1.mar
   NATS-SEFI.mar
   ISO-IR-8-1.mar
   NC_NC00-10.mar
   ISO646-CU.mar
   ISO-IR-151.mar
   NC_NC00-10%3A81.mar
   CUBA.mar
   NEXTSTEP.mar
   NEXT.mar
   NF_Z_62-010.mar
   FR.mar
   ISO646-FR.mar
   ISO-IR-69.mar
   NF_Z_62-010_%281973%29.mar
   ISO646-FR1.mar
   ISO-IR-25.mar
   NS_4551-1.mar
   NO.mar
   ISO646-NO.mar
   ISO-IR-60.mar
   NS_4551-2.mar
   NO2.mar
   ISO-IR-61.mar
   ISO646-NO2.mar
   PT.mar
   ISO646-PT.mar
   ISO-IR-16.mar
   PT154.mar
   Cyrillic-Asian.mar
   PT2.mar
   ISO646-PT2.mar
   ISO-IR-84.mar
   RK1048.mar
   STRK1048-2002.mar
   SAMI.mar
   ISO-IR-158.mar
   LAP.mar
   LATIN-LAP.mar
   WIN-SAMI-2.mar
   WINDOWS-SAMI2.mar
   WS2.mar
   SEN_850200_B.mar
   SS636127.mar
   SE.mar
   ISO646-SE.mar
   ISO646-FI.mar
   FI.mar
   ISO-IR-10.mar
   SEN_850200_C.mar
   SE2.mar
   ISO646-SE2.mar
   ISO-IR-11.mar
   SHIFT_JIS.mar
   SJIS.mar
   SHIFT_JISX0213.mar
   T%2E101-G2.mar
   ISO-IR-128.mar
   T%2E61-7BIT.mar
   ISO-IR-102.mar
   T%2E61-8BIT.mar
   ISO-IR-103.mar
   T%2E61.mar
   TCVN5712-1.mar
   TCVN5712-1%3A1993.mar
   TCVN-5712.mar
   TCVN.mar
   TIS-620.mar
   ISO-IR-166.mar
   TIS620%2E2533-0.mar
   TIS620%2E2529-1.mar
   TIS620-0.mar
   TIS620.mar
   UTF-8.mar
   ISO-10646%2FUTF-8.mar
   VIDEOTEX-SUPPL.mar
   ISO-IR-70.mar
   VISCII.mar
   WINDOWS-31J.mar
    ))

(rule
 (targets ANSI_X3%2E110-1983.mar NAPLPS.mar CSA_T500-1983.mar ISO-IR-99.mar)
 (deps    ANSI_X3.110-1983)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ANSI_X3%2E4-1968.mar CP367.mar IBM367.mar US.mar US-ASCII.mar ISO646-US.mar ASCII.mar ISO_646%2EIRV%3A1991.mar ANSI_X3%2E4-1986.mar ISO-IR-6.mar)
 (deps    ANSI_X3.4-1968)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ARMSCII-8.mar)
 (deps    ARMSCII-8)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ASMO_449.mar ISO-IR-89.mar ARABIC7.mar ISO_9036.mar)
 (deps    ASMO_449)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets BIG5.mar BIG5-CP950.mar)
 (deps    BIG5)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets BIG5-HKSCS.mar BIG5HKSCS.mar)
 (deps    BIG5-HKSCS)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets BRF.mar)
 (deps    BRF)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets BS_4730.mar UK.mar GB.mar ISO646-GB.mar ISO-IR-4.mar)
 (deps    BS_4730)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets BS_VIEWDATA.mar ISO-IR-47.mar)
 (deps    BS_VIEWDATA)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP10007.mar)
 (deps    CP10007)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP1125.mar IBM848.mar RUSCII.mar)
 (deps    CP1125)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP1250.mar MS-EE.mar)
 (deps    CP1250)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP1251.mar MS-CYRL.mar)
 (deps    CP1251)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP1252.mar MS-ANSI.mar)
 (deps    CP1252)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP1253.mar MS-GREEK.mar)
 (deps    CP1253)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP1254.mar MS-TURK.mar)
 (deps    CP1254)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP1255.mar MS-HEBR.mar)
 (deps    CP1255)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP1256.mar MS-ARAB.mar)
 (deps    CP1256)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP1257.mar WINBALTRIM.mar)
 (deps    CP1257)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP1258.mar)
 (deps    CP1258)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP737.mar)
 (deps    CP737)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP775.mar)
 (deps    CP775)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP932.mar)
 (deps    CP932)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CP949.mar)
 (deps    CP949)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CSA_Z243%2E4-1985-1.mar CA.mar CSA7-1.mar ISO646-CA.mar ISO-IR-121.mar)
 (deps    CSA_Z243.4-1985-1)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CSA_Z243%2E4-1985-2.mar CSA7-2.mar ISO646-CA2.mar ISO-IR-122.mar)
 (deps    CSA_Z243.4-1985-2)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CSA_Z243%2E4-1985-GR.mar ISO-IR-123.mar)
 (deps    CSA_Z243.4-1985-GR)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CSN_369103.mar ISO-IR-139.mar)
 (deps    CSN_369103)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets CWI.mar CP-HU.mar CWI-2.mar)
 (deps    CWI)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets DEC-MCS.mar DEC.mar)
 (deps    DEC-MCS)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets DIN_66003.mar ISO646-DE.mar DE.mar ISO-IR-21.mar)
 (deps    DIN_66003)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets DS_2089.mar DK.mar ISO646-DK.mar DS2089.mar)
 (deps    DS_2089)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-AT-DE.mar)
 (deps    EBCDIC-AT-DE)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-AT-DE-A.mar)
 (deps    EBCDIC-AT-DE-A)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-CA-FR.mar)
 (deps    EBCDIC-CA-FR)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-DK-NO.mar)
 (deps    EBCDIC-DK-NO)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-DK-NO-A.mar)
 (deps    EBCDIC-DK-NO-A)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-ES.mar)
 (deps    EBCDIC-ES)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-ES-A.mar)
 (deps    EBCDIC-ES-A)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-ES-S.mar)
 (deps    EBCDIC-ES-S)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-FI-SE.mar)
 (deps    EBCDIC-FI-SE)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-FI-SE-A.mar)
 (deps    EBCDIC-FI-SE-A)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-FR.mar)
 (deps    EBCDIC-FR)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-IS-FRISS.mar FRISS.mar)
 (deps    EBCDIC-IS-FRISS)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-IT.mar)
 (deps    EBCDIC-IT)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-PT.mar)
 (deps    EBCDIC-PT)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-UK.mar)
 (deps    EBCDIC-UK)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EBCDIC-US.mar)
 (deps    EBCDIC-US)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ECMA-CYRILLIC.mar ISO-IR-111.mar)
 (deps    ECMA-CYRILLIC)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ES.mar ISO646-ES.mar ISO-IR-17.mar)
 (deps    ES)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ES2.mar ISO646-ES2.mar ISO-IR-85.mar)
 (deps    ES2)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EUC-JISX0213.mar)
 (deps    EUC-JISX0213)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EUC-JP.mar)
 (deps    EUC-JP)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EUC-JP-MS.mar)
 (deps    EUC-JP-MS)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EUC-KR.mar)
 (deps    EUC-KR)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets EUC-TW.mar)
 (deps    EUC-TW)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets GB18030.mar)
 (deps    GB18030)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets GB2312.mar)
 (deps    GB2312)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets GBK.mar WINDOWS-936.mar MS936.mar CP936.mar)
 (deps    GBK)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets GB_1988-80.mar ISO646-CN.mar CN.mar ISO-IR-57.mar)
 (deps    GB_1988-80)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets GEORGIAN-ACADEMY.mar)
 (deps    GEORGIAN-ACADEMY)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets GEORGIAN-PS.mar)
 (deps    GEORGIAN-PS)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets GOST_19768-74.mar ISO-IR-153.mar ST_SEV_358-88.mar)
 (deps    GOST_19768-74)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets GREEK-CCITT.mar ISO-IR-150.mar)
 (deps    GREEK-CCITT)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets GREEK7.mar ISO-IR-88.mar)
 (deps    GREEK7)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets GREEK7-OLD.mar ISO-IR-18.mar)
 (deps    GREEK7-OLD)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets HP-GREEK8.mar)
 (deps    HP-GREEK8)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets HP-ROMAN8.mar R8.mar ROMAN8.mar)
 (deps    HP-ROMAN8)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets HP-ROMAN9.mar R9.mar ROMAN9.mar)
 (deps    HP-ROMAN9)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets HP-THAI8.mar THAI8.mar)
 (deps    HP-THAI8)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets HP-TURKISH8.mar TURKISH8.mar)
 (deps    HP-TURKISH8)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM037.mar EBCDIC-CP-NL.mar EBCDIC-CP-WT.mar EBCDIC-CP-CA.mar EBCDIC-CP-US.mar CP037.mar)
 (deps    IBM037)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM038.mar CP038.mar EBCDIC-INT.mar)
 (deps    IBM038)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1004.mar OS2LATIN1.mar CP1004.mar)
 (deps    IBM1004)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1026.mar 1026.mar CP1026.mar)
 (deps    IBM1026)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1047.mar 1047.mar CP1047.mar IBM-1047.mar)
 (deps    IBM1047)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1124.mar CP1124.mar)
 (deps    IBM1124)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1129.mar CP1129.mar)
 (deps    IBM1129)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1132.mar CP1132.mar)
 (deps    IBM1132)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1133.mar IBM1162.mar CP1133.mar)
 (deps    IBM1133)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1160.mar CP1160.mar)
 (deps    IBM1160)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1161.mar CP1161.mar)
 (deps    IBM1161)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1163.mar CP1163.mar)
 (deps    IBM1163)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM1164.mar CP1164.mar)
 (deps    IBM1164)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM256.mar EBCDIC-INT1.mar)
 (deps    IBM256)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM273.mar CP273.mar)
 (deps    IBM273)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM274.mar CP274.mar EBCDIC-BE.mar)
 (deps    IBM274)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM275.mar CP275.mar EBCDIC-BR.mar)
 (deps    IBM275)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM277.mar EBCDIC-CP-NO.mar EBCDIC-CP-DK.mar)
 (deps    IBM277)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM278.mar EBCDIC-CP-SE.mar EBCDIC-CP-FI.mar CP278.mar)
 (deps    IBM278)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM280.mar EBCDIC-CP-IT.mar CP280.mar)
 (deps    IBM280)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM281.mar CP281.mar EBCDIC-JP-E.mar)
 (deps    IBM281)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM284.mar EBCDIC-CP-ES.mar CP284.mar)
 (deps    IBM284)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM285.mar EBCDIC-CP-GB.mar CP285.mar)
 (deps    IBM285)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM290.mar EBCDIC-JP-KANA.mar CP290.mar)
 (deps    IBM290)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM297.mar EBCDIC-CP-FR.mar CP297.mar)
 (deps    IBM297)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM420.mar EBCDIC-CP-AR1.mar CP420.mar)
 (deps    IBM420)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM423.mar EBCDIC-CP-GR.mar CP423.mar)
 (deps    IBM423)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM424.mar EBCDIC-CP-HE.mar CP424.mar)
 (deps    IBM424)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM437.mar 437.mar CP437.mar)
 (deps    IBM437)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM500.mar EBCDIC-CP-CH.mar EBCDIC-CP-BE.mar 500V1.mar 500.mar CP500.mar)
 (deps    IBM500)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM850.mar 850.mar CP850.mar)
 (deps    IBM850)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM851.mar 851.mar CP851.mar)
 (deps    IBM851)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM852.mar 852.mar CP852.mar)
 (deps    IBM852)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM855.mar 855.mar CP855.mar)
 (deps    IBM855)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM856.mar 856.mar CP856.mar)
 (deps    IBM856)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM857.mar 857.mar CP857.mar)
 (deps    IBM857)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM860.mar 860.mar CP860.mar)
 (deps    IBM860)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM861.mar CP-IS.mar 861.mar CP861.mar)
 (deps    IBM861)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM862.mar 862.mar CP862.mar)
 (deps    IBM862)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM863.mar 863.mar CP863.mar)
 (deps    IBM863)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM864.mar CP864.mar)
 (deps    IBM864)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM865.mar 865.mar CP865.mar)
 (deps    IBM865)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM866.mar 866.mar CP866.mar)
 (deps    IBM866)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM866NAV.mar 866NAV.mar CP866NAV.mar)
 (deps    IBM866NAV)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM868.mar CP-AR.mar CP868.mar)
 (deps    IBM868)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM869.mar CP-GR.mar 869.mar CP869.mar)
 (deps    IBM869)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM870.mar EBCDIC-CP-YU.mar EBCDIC-CP-ROECE.mar CP870.mar)
 (deps    IBM870)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM871.mar EBCDIC-CP-IS.mar CP871.mar)
 (deps    IBM871)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM874.mar WINDOWS-874.mar CP874.mar)
 (deps    IBM874)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM875.mar EBCDIC-GREEK.mar CP875.mar)
 (deps    IBM875)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM880.mar EBCDIC-CYRILLIC.mar CP880.mar)
 (deps    IBM880)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM891.mar CP891.mar)
 (deps    IBM891)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM903.mar CP903.mar)
 (deps    IBM903)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM904.mar 904.mar CP904.mar)
 (deps    IBM904)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM905.mar EBCDIC-CP-TR.mar CP905.mar)
 (deps    IBM905)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM918.mar EBCDIC-CP-AR2.mar CP918.mar)
 (deps    IBM918)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IBM922.mar CP922.mar)
 (deps    IBM922)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IEC_P27-1.mar ISO-IR-143.mar)
 (deps    IEC_P27-1)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets INIS.mar ISO-IR-49.mar)
 (deps    INIS)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets INIS-8.mar ISO-IR-50.mar)
 (deps    INIS-8)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets INIS-CYRILLIC.mar ISO-IR-51.mar)
 (deps    INIS-CYRILLIC)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets INVARIANT.mar ISO-IR-170.mar)
 (deps    INVARIANT)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISIRI-3342.mar)
 (deps    ISIRI-3342)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-1.mar CP819.mar IBM819.mar L1.mar LATIN1.mar ISO_8859-1.mar ISO_8859-1%3A1987.mar ISO-IR-100.mar)
 (deps    ISO-8859-1)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-10.mar LATIN6.mar L6.mar ISO_8859-10.mar ISO_8859-10%3A1992.mar ISO-IR-157.mar)
 (deps    ISO-8859-10)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-11.mar)
 (deps    ISO-8859-11)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-13.mar L7.mar LATIN7.mar ISO-IR-179.mar)
 (deps    ISO-8859-13)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-14.mar L8.mar LATIN8.mar)
 (deps    ISO-8859-14)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-15.mar LATIN-9.mar ISO_8859-15.mar)
 (deps    ISO-8859-15)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-16.mar L10.mar LATIN10.mar ISO_8859-16.mar ISO_8859-16%3A2001.mar ISO-IR-226.mar)
 (deps    ISO-8859-16)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-2.mar L2.mar LATIN2.mar ISO_8859-2.mar ISO_8859-2%3A1987.mar ISO-IR-101.mar)
 (deps    ISO-8859-2)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-3.mar L3.mar LATIN3.mar ISO_8859-3.mar ISO_8859-3%3A1988.mar ISO-IR-109.mar)
 (deps    ISO-8859-3)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-4.mar L4.mar LATIN4.mar ISO_8859-4.mar ISO_8859-4%3A1988.mar ISO-IR-110.mar)
 (deps    ISO-8859-4)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-5.mar CYRILLIC.mar ISO_8859-5.mar ISO_8859-5%3A1988.mar ISO-IR-144.mar)
 (deps    ISO-8859-5)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-6.mar ARABIC.mar ASMO-708.mar ECMA-114.mar ISO_8859-6.mar ISO_8859-6%3A1987.mar ISO-IR-127.mar)
 (deps    ISO-8859-6)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-7.mar GREEK8.mar GREEK.mar ECMA-118.mar ELOT_928.mar ISO_8859-7.mar ISO_8859-7%3A1987.mar ISO_8859-7%3A2003.mar ISO-IR-126.mar)
 (deps    ISO-8859-7)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-8.mar HEBREW.mar ISO_8859-8.mar ISO_8859-8%3A1988.mar ISO-IR-138.mar)
 (deps    ISO-8859-8)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-9.mar L5.mar LATIN5.mar ISO_8859-9.mar ISO_8859-9%3A1989.mar ISO-IR-148.mar)
 (deps    ISO-8859-9)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-8859-9E.mar)
 (deps    ISO-8859-9E)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-IR-197.mar)
 (deps    ISO-IR-197)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-IR-209.mar)
 (deps    ISO-IR-209)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO-IR-90.mar ISO_6937-2%3A1983.mar)
 (deps    ISO-IR-90)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_10367-BOX.mar ISO-IR-155.mar)
 (deps    ISO_10367-BOX)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_11548-1.mar ISO%2FTR_11548-1.mar)
 (deps    ISO_11548-1)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_2033-1983.mar E13B.mar ISO-IR-98.mar)
 (deps    ISO_2033-1983)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_5427.mar KOI-7.mar ISO-IR-37.mar)
 (deps    ISO_5427)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_5427-EXT.mar ISO_5427%3A1981.mar ISO-IR-54.mar)
 (deps    ISO_5427-EXT)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_5428.mar ISO_5428%3A1980.mar ISO-IR-55.mar)
 (deps    ISO_5428)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_646%2EBASIC.mar ISO_646%2EBASIC%3A1983.mar REF.mar)
 (deps    ISO_646.BASIC)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_646%2EIRV.mar IRV.mar ISO_646%2EIRV%3A1983.mar ISO-IR-2.mar)
 (deps    ISO_646.IRV)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_6937.mar ISO6937.mar ISO_6937%3A1992.mar ISO-IR-156.mar)
 (deps    ISO_6937)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_6937-2-25.mar ISO-IR-152.mar)
 (deps    ISO_6937-2-25)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_6937-2-ADD.mar ISO-IR-142.mar)
 (deps    ISO_6937-2-ADD)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets ISO_8859-SUPP.mar LATIN1-2-5.mar ISO-IR-154.mar)
 (deps    ISO_8859-SUPP)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets IT.mar ISO646-IT.mar ISO-IR-15.mar)
 (deps    IT)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets JIS_C6220-1969-RO.mar ISO646-JP.mar JP.mar ISO-IR-14.mar)
 (deps    JIS_C6220-1969-RO)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets JIS_C6229-1984-B.mar JP-OCR-B.mar ISO646-JP-OCR-B.mar ISO-IR-92.mar)
 (deps    JIS_C6229-1984-B)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets JIS_X0201.mar X0201.mar)
 (deps    JIS_X0201)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets JOHAB.mar)
 (deps    JOHAB)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets JUS_I%2EB1%2E002.mar YU.mar JS.mar ISO646-YU.mar ISO-IR-141.mar)
 (deps    JUS_I.B1.002)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets JUS_I%2EB1%2E003-MAC.mar ISO-IR-147.mar MACEDONIAN.mar)
 (deps    JUS_I.B1.003-MAC)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets JUS_I%2EB1%2E003-SERB.mar SERBIAN.mar ISO-IR-146.mar)
 (deps    JUS_I.B1.003-SERB)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets KOI-8.mar)
 (deps    KOI-8)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets KOI8-R.mar)
 (deps    KOI8-R)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets KOI8-RU.mar)
 (deps    KOI8-RU)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets KOI8-T.mar)
 (deps    KOI8-T)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets KOI8-U.mar)
 (deps    KOI8-U)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets KSC5636.mar ISO646-KR.mar)
 (deps    KSC5636)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets LATIN-GREEK.mar ISO-IR-19.mar)
 (deps    LATIN-GREEK)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets LATIN-GREEK-1.mar ISO-IR-27.mar)
 (deps    LATIN-GREEK-1)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets MAC-CYRILLIC.mar)
 (deps    MAC-CYRILLIC)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets MAC-IS.mar)
 (deps    MAC-IS)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets MAC-SAMI.mar)
 (deps    MAC-SAMI)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets MAC-UK.mar)
 (deps    MAC-UK)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets MACINTOSH.mar MAC.mar)
 (deps    MACINTOSH)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets MIK.mar)
 (deps    MIK)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets MSZ_7795%2E3.mar HU.mar ISO646-HU.mar ISO-IR-86.mar)
 (deps    MSZ_7795.3)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets NATS-DANO.mar ISO-IR-9-1.mar)
 (deps    NATS-DANO)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets NATS-SEFI.mar ISO-IR-8-1.mar)
 (deps    NATS-SEFI)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets NC_NC00-10.mar ISO646-CU.mar ISO-IR-151.mar NC_NC00-10%3A81.mar CUBA.mar)
 (deps    NC_NC00-10)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets NEXTSTEP.mar NEXT.mar)
 (deps    NEXTSTEP)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets NF_Z_62-010.mar FR.mar ISO646-FR.mar ISO-IR-69.mar)
 (deps    NF_Z_62-010)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets NF_Z_62-010_%281973%29.mar ISO646-FR1.mar ISO-IR-25.mar)
 (deps    NF_Z_62-010_1973)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets NS_4551-1.mar NO.mar ISO646-NO.mar ISO-IR-60.mar)
 (deps    NS_4551-1)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets NS_4551-2.mar NO2.mar ISO-IR-61.mar ISO646-NO2.mar)
 (deps    NS_4551-2)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets PT.mar ISO646-PT.mar ISO-IR-16.mar)
 (deps    PT)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets PT154.mar Cyrillic-Asian.mar)
 (deps    PT154)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets PT2.mar ISO646-PT2.mar ISO-IR-84.mar)
 (deps    PT2)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets RK1048.mar STRK1048-2002.mar)
 (deps    RK1048)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets SAMI.mar ISO-IR-158.mar LAP.mar LATIN-LAP.mar)
 (deps    SAMI)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets WIN-SAMI-2.mar WINDOWS-SAMI2.mar WS2.mar)
 (deps    SAMI-WS2)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets SEN_850200_B.mar SS636127.mar SE.mar ISO646-SE.mar ISO646-FI.mar FI.mar ISO-IR-10.mar)
 (deps    SEN_850200_B)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets SEN_850200_C.mar SE2.mar ISO646-SE2.mar ISO-IR-11.mar)
 (deps    SEN_850200_C)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets SHIFT_JIS.mar SJIS.mar)
 (deps    SHIFT_JIS)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets SHIFT_JISX0213.mar)
 (deps    SHIFT_JISX0213)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets T%2E101-G2.mar ISO-IR-128.mar)
 (deps    T.101-G2)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets T%2E61-7BIT.mar ISO-IR-102.mar)
 (deps    T.61-7BIT)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets T%2E61-8BIT.mar ISO-IR-103.mar T%2E61.mar)
 (deps    T.61-8BIT)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets TCVN5712-1.mar TCVN5712-1%3A1993.mar TCVN-5712.mar TCVN.mar)
 (deps    TCVN5712-1)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets TIS-620.mar ISO-IR-166.mar TIS620%2E2533-0.mar TIS620%2E2529-1.mar TIS620-0.mar TIS620.mar)
 (deps    TIS-620)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets UTF-8.mar ISO-10646%2FUTF-8.mar)
 (deps    UTF-8)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets VIDEOTEX-SUPPL.mar ISO-IR-70.mar)
 (deps    VIDEOTEX-SUPPL)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets VISCII.mar)
 (deps    VISCII)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))

(rule
 (targets WINDOWS-31J.mar)
 (deps    WINDOWS-31J)
 (action  (run ../tools/camomilecharmap.exe -d . %{deps})))
